repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: fix-byte-order-marker
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
        name: Format YAML files
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        name: Lint YAML files
        args:
          - --format=parsable
          - --config-data=relaxed
  - repo: https://github.com/maxwinterstein/shfmt-py
    rev: v4.0.0
    hooks:
      - id: shfmt
        name: Format shell scripts
        args:
          - -i=2
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        name: Lint shell scripts
  - repo: https://github.com/reteps/dockerfmt
    rev: v0.5.4
    hooks:
      - id: dockerfmt
        name: Format Dockerfiles
        args:
          - --indent=4
          - --newline
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.14.0
    hooks:
      - id: hadolint
        name: Lint Dockerfiles
ci:
  autofix_commit_msg: "chore(pre-commit): auto-fix pre-commit issues"
  autofix_prs: true
  autoupdate_commit_msg: "chore(pre-commit): auto-update pre-commit hooks"
  autoupdate_schedule: weekly
